version: '3.8'

services:
  notypdf:
    image: drakonis96/notypdf:latest
    ports:
      - "5026:5026"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - NOTION_API_KEY=${NOTION_API_KEY}
    volumes:
      - data:/app/data
      - workspace:/myworkspace
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: pdf-reader-network

volumes:
  data:
  workspace:
